### PR TITLE
Pin object muxed pins

### PR DESCRIPTION
**Pull request by kubalewski**

### CODE REVIEW

**Comment by mwolech** [comment]
@vvfedorenko could you please review?

**Comment by vvfedorenko** [comment]
Hi @mwolech! Sorry for the delay, will take a look right now

**Comment by vvfedorenko** [comment]
The first blocker here is that *ice* changes are in the same commit as changes to the subsystem itself. AFAIR, Arkadiusz said that these changes are not ready to upstream, I really would like to them as a separate commit after all the changes to the subsystem.

**Comment by vvfedorenko** [comment]
Another thing I don't really like is this double-mutex locking. It really opens the door for dead-locking if we are not careful in the future. @kuba-moo what do you think about it? Could you suggest something instead of double-mutexes?

**Comment by kuba-moo** [comment]
Lots of locks, can't pins be protected by the lock of the dpll device they belong to?

**Comment by vvfedorenko** [comment]
Not actual anymore

**Pull request closed without merging**
