### PR TITLE
Pin object muxed pins

### PR DESCRIPTION
**Pull request by mwolech**

### CODE REVIEW

**Comment by mwolech** [comment]
Hi @vvfedorenko! To avoid misunderstandings and have a possibility to keep Arek's implementation unchanged in case of any problems, I've created my own fork and copied Arek's code with fixes after your review.

Could you please review commits? 

+ We've discussed your concerns about double-mutex locking in the team and we were considering refcounts and atomic APIs, but our understanding is that it's not a legitimate method as pins may be shared between various resources (various dplls). Could you please review current implementation and share your thoughts about that?

**Comment by vvfedorenko** [comment]
Hi @mwolech!
It looks like we have to re-think the way we accounting pins. As you said, we would like to have absolutely separate list of pins that can potentially be connected to different dpll devices. Anfd we would also like to have a mux device that will have connected pins too. But what I can see in the code is that pin is allocated from the xarray of dpll or mux device and then added to the global list. How can it be then connected to another dpll device?
My suggestion is to have global xarray of the pins and store a pointer to the pin in the dpll/mux device. The problem is how to define a scope of devices that can use pin object, because we don't really want to have a "rogue" driver which can steal any pin of any device in the system.

**Comment by vvfedorenko** [comment]
One more comment about locks. Once we got to the ref-counting, I think we have to remove mutexes and make refcounts atomic (there is special type in kernel for refcounting). and create pin_get/pin_put functions and use them once the code is referencing a pin object. Otherwise it looks really strange.

**Comment by vvfedorenko** [comment]
And one more comment - we have to have a way to switch type of the pin from source to output and back. We already have such kind of pins in our OCP TimeCard. I would like to merge source, output and mux types into one structure and change the behavior based on the type assigned.

**Comment by kuba-moo** [comment]
Can you say more about "pins that can potentially be connected to different dpll devices"?
Inside the package the same pin is routed to two DPLL instances?

**Comment by mwolech** [comment]
@kuba-moo - I'm wondering if it's a valid usage of the DPLL interface, maybe we should share DPLLs instead of creating global pins? There are challenges, for example (as Vadim mentioned) define a scope of devices that can use pin object, provide a protection to avoid freeing pins that are acquired by the different devices etc. What do you think?

**Comment by kuba-moo** [comment]
My instinct was that if we want to describe that pins share an input / trace / are connected we should do it in a way similar to a mux, rather than having two dplls link up to the same pin.
Separate the description of the topology (and constraints on valid configurations which the topology implies) from the configuration of the DPLL inputs.
But that's just my instinct, could well be wrong...

**Comment by mwolech** [comment]
@kuba-moo thanks for the suggestion! I'm not an expert in mux implementation, but I'll get familiar and consider that. Current idea is to allocate pins on the driver side and assign them to specific DPLL that can be shared between several instances. My inspiration was current implementation of programmable pins, I think that the concept can be similar. Code has been partially adjusted, I'm still working on that.

**Comment by kubalewski** [comment]
> Hi @mwolech! It looks like we have to re-think the way we accounting pins. As you said, we would like to have absolutely separate list of pins that can potentially be connected to different dpll devices. Anfd we would also like to have a mux device that will have connected pins too. But what I can see in the code is that pin is allocated from the xarray of dpll or mux device and then added to the global list. How can it be then connected to another dpll device? My suggestion is to have global xarray of the pins and store a pointer to the pin in the dpll/mux device. The problem is how to define a scope of devices that can use pin object, because we don't really want to have a "rogue" driver which can steal any pin of any device in the system.

Hi!
Hmm, I think this draft PR is somehow broken, some of the functions are missing. Please refer to my original PR.

About list of pins, actually it is already the other way around, the pin is first allocated on "global" list of pins (with dpll_pin_alloc(...)), and then it can be registered with a single or many dplls (with dpll_pin_register(...)).
Of course we can change it to global xarray instead of global double linked list.
Once the pin is registered with a dpll, it cannot be removed from the global list (dpll_pin_free(...), unless all dplls have it deregistered.

For separated drivers connecting pins to one dpll, it would be:
- one driver allocates and registers dpll (can also add pins)
- the others would have to: find the dpll, and then allocate and register pins with it (exported dpll_device_get_by_name(...) allows to find a dpll)

I ve been thinking on how to prevent malicious drivers from messing around, but I cannot find good enough solution.
Such malicious driver is able to find a dpll (with its name) and mess around, find pins, deregister them, deregister/free dpll, etc.
If the user is able to load such malicious driver, it could also damage OS with other tools, couldn't he?

> My instinct was that if we want to describe that pins share an input / trace / are connected we should do it in a way similar to a mux, rather than having two dplls link up to the same pin. 

Multiple dplls can use the same set of pins, this is why first allocating pins on global list then registering them with dpll(s).

> Separate the description of the topology (and constraints on valid configurations which the topology implies) from the configuration of the DPLL inputs. But that's just my instinct, could well be wrong...

This implementation has "muxed pins", they are allocated same as regular pins, but the driver would have to register them to different pins instead of registering them with a dpll (dpll_muxed_pin_register(...))
That is why dpll_pin_get_by_name(...) and dpll_pin_get_by_id(...) are exported, the driver can find a pin (already registered to a dpll device), and connect new pin to it, the pin ops in this case would belong to that driver.
For netlink part, "muxed pins" would iterate over its registered pins during dumps.

Do I understand "Separate the description of the topology (and constraints on valid configurations which the topology implies) from the configuration of the DPLL inputs." correctly as it would be better to remove muxed word from the function names?
Or that wasn't your point?

Please let me know about anything that can be improved.
I will incorporate comments as well as ones from netdev (from Jiri Pirko) and will try to finalize things.

**Comment by MaciekMachni** [comment]
Hi

I'm lost. Why would pins need to be global if the only way to search them is through a DPLL that owns them.
Let's get back to drawing board and try to define the problem we're trying to solve. Let's also define what the pin represents.

The problem of a single CGU with multiple DPLLs inside:
In this case all DPLLs inside a single chip will be controlled by the same DPLL driver instance. It can be solved by attaching the pins to the DPLL object and sharing the pins structure between different DPLLs inside one chip. That would result in a much cleaner solution than a globally allocated pins living inside the kernel forever.

The problem of sharing the CGU package between multiple devices:
In this case a single CGU chip will hook up to different devices. This problem should be solved differently. The device that has a physical connection to the package needs to allocate DPLL objects with the respective pins and other devices that use the same DPLL needs to link to it, just like we do with a single PHC linking to multiple netdevs. Otherwise the control would not work, as if you issue some command to the pin it will not know where to go.

**Comment by kubalewski** [comment]
> Hi
> 
> I'm lost. Why would pins need to be global if the only way to search them is through a DPLL that owns them. Let's get back to drawing board and try to define the problem we're trying to solve. Let's also define what the pin represents.
>

Hi Maciej!

Pins itself are not global for the interface users, the list storing pins is global.
Basically we shall not have a pin which is not connected anywhere. It is possible to do so, but only with wrong usage of this interface. Same as allocating and not freeing the memory is not proper way of using malloc.
With the idea of sharing pins, we must store them somewhere, pins are allocated globally but as long as there is no dpll using it, it cannot be shared. Once pins is allocated and registered with one of exisiting dplls then other dpll is able to find it and register with it.

There is Milena's idea to let the driver handle the pins (allocate and keep them in a driver's memory shared between driver instances).

> The problem of a single CGU with multiple DPLLs inside: In this case all DPLLs inside a single chip will be controlled by the same DPLL driver instance.

This is not CGU interface, although CGU can be supported by it.
What about case where multiple dplls are not a single integrated circuit, but they still share sources?

> It can be solved by attaching the pins to the DPLL object and sharing the pins structure between different DPLLs inside one chip. That would result in a much cleaner solution than a globally allocated pins living inside the kernel forever.

I am sorry but I don't get this part: "sharing the pins structure between different DPLLs inside one chip", dplls are right now separated software objects, and this implementation actually allows to share the pins/register single pin with multiple dplls.

> 
> The problem of sharing the CGU package between multiple devices: In this case a single CGU chip will hook up to different devices.

There is no such thing like CGU in this interface :)

>This problem should be solved differently. The device that has a physical connection to the package needs to allocate DPLL objects with the respective pins and other devices that use the same DPLL needs to link to it, just like we do with a single PHC linking to multiple netdevs. Otherwise the control would not work, as if you issue some command to the pin it will not know where to go.

Could you please restate this problem, knowing we have separated dplls (each controlled by a driver that did dpll alloc/registration) and a number of pins registered with dpll (where pins are controlled (with dpll_pin_ops) by the driver instance that allocated given pin).

**Comment by MaciekMachni** [comment]
> > Hi
> > I'm lost. Why would pins need to be global if the only way to search them is through a DPLL that owns them. Let's get back to drawing board and try to define the problem we're trying to solve. Let's also define what the pin represents.
> 
> Hi Maciej!
> 
> Pins itself are not global for the interface users, the list storing pins is global. Basically we shall not have a pin which is not connected anywhere. It is possible to do so, but only with wrong usage of this interface. Same as allocating and not freeing the memory is not proper way of using malloc. With the idea of sharing pins, we must store them somewhere, pins are allocated globally but as long as there is no dpll using it, it cannot be shared. Once pins is allocated and registered with one of exisiting dplls then other dpll is able to find it and register with it.
> 
> There is Milena's idea to let the driver handle the pins (allocate and keep them in a driver's memory shared between driver instances).

That sounds much better and safer.
Current implementation with a global structure has a lot of hidden assumptions - such as a single pin can only be used by one driver type. For example current set_prio implementation for ice lands in the ice_synce_set_source_prio which assumes that the DPLL it handles is only the one that ice comes with. If you link a different DPLL to that pin the whole implementation will explode.
Also priorities should be a property of a DPLL, not of a pin.

> 
> > The problem of a single CGU with multiple DPLLs inside: In this case all DPLLs inside a single chip will be controlled by the same DPLL driver instance.
> 
> This is not CGU interface, although CGU can be supported by it. What about case where multiple dplls are not a single integrated circuit, but they still share sources?

We can call it clock generator, network synchronizer, CGU - in general I'm talking about a single package that packs couple DPLLs internally. 
If we talk about separate chips they should be handled by separate drivers and have separate pins. Connections between those pins should be handled in the userspace using some kind of a config file. Otherwise we will bloat the kernel with a multitude of possible connections between them. If we want to implement some support for that we'd need to configure that using the device tree or a similar mechanism.

> 
> > It can be solved by attaching the pins to the DPLL object and sharing the pins structure between different DPLLs inside one chip. That would result in a much cleaner solution than a globally allocated pins living inside the kernel forever.
> 
> I am sorry but I don't get this part: "sharing the pins structure between different DPLLs inside one chip", dplls are right now separated software objects, and this implementation actually allows to share the pins/register single pin with multiple dplls.

But those objects for a single chip will be created by a single driver. This means that those pins can easily be allocated once and shared with other DPLLs that use the same physical connections.
 
> > The problem of sharing the CGU package between multiple devices: In this case a single CGU chip will hook up to different devices.
> 
> There is no such thing like CGU in this interface :)

> > This problem should be solved differently. The device that has a physical connection to the package needs to allocate DPLL objects with the respective pins and other devices that use the same DPLL needs to link to it, just like we do with a single PHC linking to multiple netdevs. Otherwise the control would not work, as if you issue some command to the pin it will not know where to go.
> 
> Could you please restate this problem, knowing we have separated dplls (each controlled by a driver that did dpll alloc/registration) and a number of pins registered with dpll (where pins are controlled (with dpll_pin_ops) by the driver instance that allocated given pin).

Before we get there I'd need to understand what a "pin", as we need to attach correct properties to the right objects.
I.e. DPLLs should operate on sources and outputs - if we want to separate pins from that - we should link them to either of those. Anyways, I'll try my best:

Assumption 1: You cannot create a pin with properties that will be universally shared, because you don't know what features will other DPLLs that tries to attach to it have.
Assumption 2: as a result of 1 - we are not sharing pins between the devices that are not part of the same chip (driven by the same driver)

With those:
The driver that controls a given IC containing one or multiple DPLLs will allocate pins in its memory - may allocate all of them at once for a better performance.
Once they are allocated - it can either reuse the same pin list for other DPLLs handled by this driver, or can use a subset of them (i.e. by using xarrays if needed).
A change in a pin object will then trigger an action in each DPLL that it is linked to (i.e. change of direction, or change of expected frequency).

**Comment by kubalewski** [comment]
>That sounds much better and safer.

Not sure about safer, the list in the driver would be also static/global and shared by all instances of the driver, so only the place of vulnerability would change.
The problem here: where memory of pin shall be managed, in the driver or in the kernel.
For driver it increase complexity for each driver implementing it.
For kernel it increase complexity in one place.

I can go with either approach as long as we all have agreement.

>Current implementation with a global structure has a lot of hidden assumptions - such as a single pin can only be used by one driver type. For example current set_prio implementation for ice lands in the ice_synce_set_source_prio which assumes that the DPLL it handles is only the one that ice comes with. If you link a different DPLL to that pin the whole implementation will explode.

Sorry but i don't get the first part "a single pin can only be used by one driver type.", a pin is first allocated, then it must be registered with dpll, once done any other kernel module can find such dpll, it's pins and register any of the pins with its own dpll.

Example is good catch, this must change, setting prio is dpll level command, requires three arguments, dpll_id, pin_id and prio, as priority is set for a pin on a one of dplls it is connected to.
Will fix that.

>Also priorities should be a property of a DPLL, not of a pin.

Can't agree entirely, value of pin priority is associated with both dpll and a pin.
But sure, as explained above, I will move get/set prio back to dpll ops.

>We can call it clock generator, network synchronizer, CGU - in general I'm talking about a single package that packs couple DPLLs internally.

Well, exactly opposite, it is called dpll subsystem, which allows the user to control dpll.
Individual dplls can use and share same inputs.
Which can be then used to handle CGU/package/network synchronizer.
But dpll is still a separated object here with ability to share sources.

>If we talk about separate chips they should be handled by separate drivers and have separate pins. 

This is only assumption, right?
Sorry but I don't see the reason why they should be handled by separated drivers and have separated pins, as we are trying to have generic dpll interface.

>Connections between those pins should be handled in the userspace using some kind of a config file.

IMHO opposite, userspace shall ask dpll for the config and receive it, it is driver role to provide input for dpll subsystem, and driver is supposed to be middleware between HW and user, so for me everything is fine with this approach.
As I understand idea for generic dpll interface was to eliminate any vendor specific config files.

>Otherwise we will bloat the kernel with a multitude of possible connections between them. If we want to implement some support for that we'd need to configure that using the device tree or a similar mechanism.

HW connections are known by HW, SW driver must be able to provide them for HW it handles, and DPLL subsystem provides this info to the user.
I don't get or like idea where this interface would use any HW specific config file. This doesn't make much sense, as it would become some kind of FW loader at this point.

>But those objects for a single chip will be created by a single driver.
>This means that those pins can easily be allocated once and shared with other DPLLs that use the same physical connections.
Again looks like assumption, it is true in our case, at least in present use cases.
But this is supposed to be generic interface, some users might have some different approach, thus I don't think there is value added in forcing all kernel-space users to allocate two or more dplls from single instance of a driver.

>Before we get there I'd need to understand what a "pin", as we need to attach correct properties to the right objects.

"pin" is an object that can be either source or output.
Right now:
- type is being set on allocation of a pin (but as Vadim already requested, there is need to change between types on the fly, so there is a need for get/set on pin's direction from userspace and callback associated with it)
- attributes of pins dumped to the user are selected based on pin type
- a "pin" can be also muxed pin, which is done be registering a new pin with already existing pin, this allows another layer of pins to be connected to a pin that is directly connected to a dpll. Clock recovery mechanism could use this feature and allow user to select one of clock recovery pins as a source for its parent pin.


>I.e. DPLLs should operate on sources and outputs - if we want to separate pins from that - we should link them to either of those. Anyways, I'll try my best:
>Assumption 1: You cannot create a pin with properties that will be universally shared, because you don't know what features will other DPLLs that tries to attach to it have.

Based on pin type and implemented ops the user will get proper info.
For sure not all the properities are required to be shared, but most of them can be universal.
For now "pin" can share a name, id, frequency, in the future: phase_offset, some features.
I.e. changing frequency of a pin is handled by the driver that allocated the pin, but all the dplls connected with it shall be notified about it. Which is also a great finding and needs to be fixed/implemented. 

>Assumption 2: as a result of 1 - we are not sharing pins between the devices that are not part of the same chip (driven by the same driver)
I don't fully understand what is the problem, could you please give an example of such situation?

>With those:
>The driver that controls a given IC containing one or multiple DPLLs will allocate pins in its memory - may allocate all of them at once for a better performance.

I don't expect performance issues here :)

>Once they are allocated - it can either reuse the same pin list for other DPLLs handled by this driver, or can use a subset of them (i.e. by using xarrays if needed).

This is easily achievable right now with one instance of a driver, as allocating pins returns the pin pointer which can be used to register pin in second dpll just like that, sorry this part is missing in "ice" example.
A single kernel module instance that handles multiple dplls doesn't have to look for pins, it can just register them with another dpll. 

Searching for a dpll and its pins is required by dpll subsystem users which want use multiple driver instances for dpll or pin initialization (required for sophisticated multi-Firmware solutions).

>A change in a pin object will then trigger an action in each DPLL that it is linked to (i.e. change of direction, or change of expected frequency).

Yes, as stated above, such mechanics is missing. I will try to fix it, so all dplls that registered a pin will get such update.

**Comment by kuba-moo** [comment]
We should probably have this conversation on the ML, otherwise we'll have to repeat again to Jiri :/

**Comment by MaciekMachni** [comment]
> > Current implementation with a global structure has a lot of hidden assumptions - such as a single pin can only be used by one driver type. For example current set_prio implementation for ice lands in the ice_synce_set_source_prio which assumes that the DPLL it handles is only the one that ice comes with. If you link a different DPLL to that pin the whole implementation will explode.
> 
> Sorry but i don't get the first part "a single pin can only be used by one driver type.", a pin is first allocated, then it must be registered with dpll, once done any other kernel module can find such dpll, it's pins and register any of the pins with its own dpll.

It won't work in the kernel. Driver A will not know which pins were allocated by Driver B. Even in the reference code submitted to the ICE driver all pins and DPLLs created by multiple ice devices will have the same names, and you'll get a bunch of pins named OCXO of DPLL0.

> 
> > Also priorities should be a property of a DPLL, not of a pin.
> 
> Can't agree entirely, value of pin priority is associated with both dpll and a pin. But sure, as explained above, I will move get/set prio back to dpll ops.
> 
> > We can call it clock generator, network synchronizer, CGU - in general I'm talking about a single package that packs couple DPLLs internally.
> 
> Well, exactly opposite, it is called dpll subsystem, which allows the user to control dpll. Individual dplls can use and share same inputs. Which can be then used to handle CGU/package/network synchronizer. But dpll is still a separated object here with ability to share sources.

I really wanted to avoid getting into naming discussions again.
A DPLL is a very well-defined object that takes a single reference frequency and generates the output signal that is related to the phase of the input signal. What this subsystem tries to implement is called Clock Synchronizer (if it has inputs and outputs) or a Clock Generator (if it has no inputs other than an oscillator). Such device integrates an input block with reference monitoring and conditioning, a DPLL(s) block and an output block that generates output frequencies + control logic.

> > If we talk about separate chips they should be handled by separate drivers and have separate pins.
> 
> This is only assumption, right? Sorry but I don't see the reason why they should be handled by separated drivers and have separated pins, as we are trying to have generic dpll interface.
> 
> > Connections between those pins should be handled in the userspace using some kind of a config file.
> 
> IMHO opposite, userspace shall ask dpll for the config and receive it, it is driver role to provide input for dpll subsystem, and driver is supposed to be middleware between HW and user, so for me everything is fine with this approach. As I understand idea for generic dpll interface was to eliminate any vendor specific config files.
>
> > Otherwise we will bloat the kernel with a multitude of possible connections between them. If we want to implement some support for that we'd need to configure that using the device tree or a similar mechanism.
> 
> HW connections are known by HW, SW driver must be able to provide them for HW it handles, and DPLL subsystem provides this info to the user. I don't get or like idea where this interface would use any HW specific config file. This doesn't make much sense, as it would become some kind of FW loader at this point.
>

This is not implementable in the kernel without having a separate driver for each custom board one may design, or support in some well-defined solution to address that, such as a device tree. I.e. customer A will use the the Clock Generator X and Y and connect output 1 of X to reference 5 of Y, and customer B will use the Clock Generator Y and Z and connect the output 1 of X to reference 2 of Y. How this API will be able to handle all combinations without modifying the driver?

> > But those objects for a single chip will be created by a single driver.
> > This means that those pins can easily be allocated once and shared with other DPLLs that use the same physical connections.
> > Again looks like assumption, it is true in our case, at least in present use cases.
> > But this is supposed to be generic interface, some users might have some different approach, thus I don't think there is value added in forcing all kernel-space users to allocate two or more dplls from single instance of a driver.
> 
> > Before we get there I'd need to understand what a "pin", as we need to attach correct properties to the right objects.
> 
> "pin" is an object that can be either source or output. Right now:
> 
> * type is being set on allocation of a pin (but as Vadim already requested, there is need to change between types on the fly, so there is a need for get/set on pin's direction from userspace and callback associated with it)
> * attributes of pins dumped to the user are selected based on pin type
> * a "pin" can be also muxed pin, which is done be registering a new pin with already existing pin, this allows another layer of pins to be connected to a pin that is directly connected to a dpll. Clock recovery mechanism could use this feature and allow user to select one of clock recovery pins as a source for its parent pin.

In that case a "pin" (we should really come up with a better name for it) should only be a container of function pointers linking to the given DPLL(s) references or outputs + necessary flags, as it represent a connection between objects.

Such object will be able to model 4 different things:
1. Input pin (only linked to references)
2. Output pin (only linked to outputs)
3. Input/Output pin (linked to references and outputs with type IO pin)
4. Connection between the source of 1 and the reference of another object (linked to one output of one object and references of another objects).

It should be completely abstract (not link to any specific driver) and all this object would do is to call the functions of linked "DPLLs".

And the new "DPLL" subsystem should stick to references and outputs to model the device that it actually drives.

> > Assumption 2: as a result of 1 - we are not sharing pins between the devices that are not part of the same chip (driven by the same driver)
> > I don't fully understand what is the problem, could you please give an example of such situation?
> 
> > With those:
> > The driver that controls a given IC containing one or multiple DPLLs will allocate pins in its memory - may allocate all of them at once for a better performance.
> 
> I don't expect performance issues here :)

Linux runs on a multitude of devices - not only on 64-core EPYC servers. Especially a subsystem that manages clocks wouldn't run there.

**Comment by MaciekMachni** [comment]
> We should probably have this conversation on the ML, otherwise we'll have to repeat again to Jiri :/

DPLL pins were not yet submitted to the ML, but I'll make him aware of that PR.

**Comment by jpirko** [comment]
> We should probably have this conversation on the ML, otherwise we'll have to repeat again to Jiri :/

Exactly. I don't understand why this is being developed/discussed on the side. Please, have this on netdev mailing list and close this repo, it is very misleading. Thanks!

**Comment by jpirko** [comment]
> My instinct was that if we want to describe that pins share an input / trace / are connected we should do it in a way similar to a mux, rather than having two dplls link up to the same pin. Separate the description of the topology (and constraints on valid configurations which the topology implies) from the configuration of the DPLL inputs. But that's just my instinct, could well be wrong...

A agree, have the same feeling. The idea of "global pins" sound very wrong to me.

**Comment by jpirko** [comment]
> > Hi
> > I'm lost. Why would pins need to be global if the only way to search them is through a DPLL that owns them. Let's get back to drawing board and try to define the problem we're trying to solve. Let's also define what the pin represents.
> 
> Hi Maciej!
> 
> Pins itself are not global for the interface users, the list storing pins is global. Basically we shall not have a pin which is not connected anywhere. It is possible to do so, but only with wrong usage of this interface. Same as allocating and not freeing the memory is not proper way of using malloc. With the idea of sharing pins, we must store them somewhere, pins are allocated globally but as long as there is no dpll using it, it cannot be shared. Once pins is allocated and registered with one of exisiting dplls then other dpll is able to find it and register with it.

I believe that instead of a "global pin beast", you can just stick with "pin-associated with dpll". If the same pin is associated possibly with 2 dplls, you can have the pin created twice, once for each dpll instance. By default, the pin is used with dpll1 for example. The pin "personality" in dpll2 is going to be shown as "disconnected". This will provide you possibily to:

- disconnect/connect the pins in multiple instances independently
- the driver is going to do the sanitization - in case the pin is connected on dpll1 and user wants to connect it on dpll2, it can forbid it with proper extack message.
- if it is possible to have the pin to be connected as a source pin to both dpll2 (if the hw supports it), driver will allow and the user is going to have the visibility about it.

**Comment by kubalewski** [comment]
>>>Current implementation with a global structure has a lot of hidden assumptions - such as a single pin can only be used by one driver type. For example current set_prio implementation for ice lands in the ice_synce_set_source_prio which assumes that the DPLL it handles is only the one that ice comes with. If you link a different DPLL to that pin the whole implementation will explode.

>>Sorry but i don't get the first part "a single pin can only be used by one driver type.", a pin is first allocated, then it must be registered with dpll, once done any other kernel module can find such dpll, it's pins and register any of the pins with its own dpll.

>It won't work in the kernel. Driver A will not know which pins were allocated by Driver B. Even in the reference code submitted to the ICE driver all pins and DPLLs created by multiple ice devices will have the same names, and you'll get a bunch of pins named OCXO of DPLL0.

It works right now, as long as driver is using the interface in the way it should be using it.
But this is great catch again, I can make it more durable and less vurnable for such behavior.

I will add code to prevent allocation of dpll with the same name. As it is up to the driver to either give a dpll name or not. In case of already registered name, it is reasonable to fail the allocation.

Even if all the pins have the same name, the driver A must still be able to find different pins registered with driver's B dpll - I will handle this somehow.
Currently pin id is given by registerer on allocation, but this will change, pin id is needed in two cases: first for the userspace part, so the user is able to select one of dpll's pins (to get/set things), second for the kernel part, thus any driver can find pin registered with exisitng dpll.

It looks like you are still refering to the global list of pins.
Which makes me think that you still don't fully understand the idea of how it is sopposed to work. Sorry, it seems I am bad in explanation.

Global list of pins is a place to store allocated pointer of pins, it is not used for any other reason. Basically you could allocate a thousand of pins with the same name and same ops. But no one is able to find them, or confuse them in any matter, this is internal way of storing them, not a way to provide it to anyone.

Pins on kernelspace part shall be able to be found only once they are registered with a dpll, and this is also for a reason. As pins are separated objects for implemetation purposes, they shall never be seen separated from dpll, for the user or kernel module POV. In order to share something, this must be used by more then one entity, so one entity needs to create and use it, second entity can only find it, use it, and get notfied if it's properity has changed.

> I really wanted to avoid getting into naming discussions again.
> A DPLL is a very well-defined object that takes a single reference frequency and generates the output signal that is related to the phase of the input signal. What this subsystem tries to implement is called Clock Synchronizer (if it has inputs and outputs) or a Clock Generator (if it has no inputs other than an oscillator). Such device integrates an input block with reference monitoring and conditioning, a DPLL(s) block and an output block that generates output frequencies + control logic.

Yes, that is true, but such simple dpll doesn't really need any control.
Here the dpll subsystem is an interface that allows for software control point over any device using dpll.
For such simple dpll the user could have one input one output and maybe some status monitoirng, but at least user can know that it exist.
For more complex solutions with added inputs, outputs and control over them.
For most complex ones, like CGU you mentioned, it shall be also able to share the sources between many dplls.

This is why we want it to be generic and serve all use cases we can think of right now.

Naming here is crucial as new subsystem shall have name showing it's purpose.

>This is not implementable in the kernel without having a separate driver for each custom board one may design, or support in some well-defined solution to address that, such as a device tree. I.e. customer A will use the the Clock Generator X and Y and connect output 1 of X to reference 5 of Y, and customer B will use the Clock Generator Y and Z and connect the output 1 of X to reference 2 of Y. How this API will be able to handle all combinations without modifying the driver?

Sorry but now I am lost :) I don't understand those use cases or I am missing something here.
First of all for my understanding "custom" implies that the support in the driver is also required: custom board -> custom driver.

But anyway could you please elaborate? Are there typos in those names X, Y, Z? As customer B example says about Y and Z, but connects with X and Y?
If I understand Customer A example correctly:
"output 1 of X" (a source type pin) registered with "reference 5 of Y" (a muxed, source type pin)

>In that case a "pin" (we should really come up with a better name for it) should only be a container of function pointers linking to the given DPLL(s) references or outputs + necessary flags, as it represent a connection between objects.

>Such object will be able to model 4 different things:

>1. Input pin (only linked to references)
>2. Output pin (only linked to outputs)
>3. Input/Output pin (linked to references and outputs with type IO pin)
>4. Connection between the source of 1 and the reference of another object (linked to one output of one object and references of another objects).
>It should be completely abstract (not link to any specific driver) and all this object would do is to call the functions of linked "DPLLs".

>And the new "DPLL" subsystem should stick to references and outputs to model the device that it actually drives.

Well, yeah, we more or less trying to come up with something like you have described here.

>Linux runs on a multitude of devices - not only on 64-core EPYC servers. Especially a subsystem that manages clocks wouldn't run there.

Sorry but I still don't understand what performance issue we are seeing here.

**Comment by kubalewski** [comment]
> > We should probably have this conversation on the ML, otherwise we'll have to repeat again to Jiri :/
> 
> DPLL pins were not yet submitted to the ML, but I'll make him aware of that PR.

Once we have new version we could probably go there!

**Comment by kubalewski** [comment]
>I believe that instead of a "global pin beast", you can just stick with "pin-associated with dpll". If the same pin is associated possibly with 2 dplls, you can have the pin created twice, once for each dpll instance. By default, the pin is used with dpll1 for example. The pin "personality" in dpll2 is going to be shown as "disconnected". This will provide you possibily to:

>- disconnect/connect the pins in multiple instances independently
>- the driver is going to do the sanitization - in case the pin is connected on dpll1 and user wants to connect it on dpll2, it can forbid it with proper extack message.
>- if it is possible to have the pin to be connected as a source pin to both dpll2 (if the hw supports it), driver will allow and the user is going to have the visibility about it.

I see your point, will try to think how to implement something alike with next version.

**Comment by jpirko** [comment]
> > > We should probably have this conversation on the ML, otherwise we'll have to repeat again to Jiri :/
> > 
> > 
> > DPLL pins were not yet submitted to the ML, but I'll make him aware of that PR.
> 
> Once we have new version we could probably go there!

Please do and stay there with all discussions and other submissions. Much easier to follow. Thanks!

**Comment by MaciekMachni** [comment]
> Global list of pins is a place to store allocated pointer of pins, it is not used for any other reason. Basically you could allocate a thousand of pins with the same name and same ops. But no one is able to find them, or confuse them in any matter, this is internal way of storing them, not a way to provide it to anyone.
> 
> Pins on kernelspace part shall be able to be found only once they are registered with a dpll, and this is also for a reason. As pins are separated objects for implemetation purposes, they shall never be seen separated from dpll, for the user or kernel module POV. In order to share something, this must be used by more then one entity, so one entity needs to create and use it, second entity can only find it, use it, and get notfied if it's properity has changed.

This shows that they belong to DPLLs and there's no need to make them global to the whole kernel. Maybe we should make register pin a property of DPLL subsystem and not a global function? In this case you would need to find the DPLL in question and call register pin on it to register any dependency/additional source. That would get rid of many xarrays to control.

> Sorry but now I am lost :) I don't understand those use cases or I am missing something here. First of all for my understanding "custom" implies that the support in the driver is also required: custom board -> custom driver.
> 
> But anyway could you please elaborate? Are there typos in those names X, Y, Z? As customer B example says about Y and Z, but connects with X and Y? If I understand Customer A example correctly: "output 1 of X" (a source type pin) registered with "reference 5 of Y" (a muxed, source type pin)
> 

Let's have a board global DPLL on the platform placed on the motherboard. Now plug in the NIC A and NIC B into it - each coming with its own DPLL. How would the NIC DPLL find the one on the motherboard? To make it happen you would need a separate driver for each combination of interconnected pins and DPLLs with no generic mechanism to abstract that.

Anyways, let's wait for the next revision of patches and continue this discussion on the ML.

**Pull request closed without merging**
